#!/usr/bin/env python3
##
## HACKATOWN PROJECT, 2021
## Hackatown-2021
## File description:
## main file
##

import sys
import os
import io
import folium

from PySide2 import QtCore, QtWidgets
from PySide2.QtGui import QIcon
from PySide2.QtWidgets import QApplication, QMainWindow, QVBoxLayout, QWidget
from PySide2.QtCore import QFile
from PySide2.QtUiTools import QUiLoader
from PyQt5.QtWebEngineWidgets import QWebEngineView


class AerialMap(QWidget):
    def load_ui(self):
        layout = QVBoxLayout()
        self.setLayout(layout)

        coordinates = (37.8198, -122.4785)
        m = folium.Map(
            title = "TODO",
            zoom_start = 13,
            location = coordinates
        )
        data = io.BytesIO()
        m.save(data, close_file=False)

        web_view = QWebEngineView()
        web_view.setHtml(data.getvalue().decode())
        layout.addWidget(web_view)

    def __init__(self):
        super(AerialMap, self).__init__()
        self.load_ui()


class MainWindow(QMainWindow):
    def set_values(self):
        self.window_height = 800
        self.window_width = 1200
        self.setMinimumSize(self.window_width, self.window_height)
        self.setWindowTitle("TODO")
        self.setWindowIcon(QIcon("TODO.png"))

    def load_ui(self):
        loader = QUiLoader()
        path = os.path.join(os.path.dirname(__file__), "form.ui")
        ui_file = QFile(path)
        ui_file.open(QFile.ReadOnly)
        loader.load(ui_file, self)
        ui_file.close()

    def __init__(self):
        super(MainWindow, self).__init__()
        self.set_values()
        self.load_ui()


if __name__ == "__main__":
    QtCore.QCoreApplication.setAttribute(QtCore.Qt.AA_ShareOpenGLContexts)
    app = QApplication([])
    widget = MainWindow()
    map_widget = AerialMap()
    widget.show()
    map_widget.show()
    sys.exit(app.exec_())
