#!/usr/bin/env python3
##
## HACKATOWN PROJECT, 2021
## Hackatown-2021
## File description:
## main file
##

import sys
from PyQt5 import QtWidgets
from ClassMainWindow import MainWindow

def main():
    app = QtWidgets.QApplication([])
    widget = MainWindow()
    widget.show()
    sys.exit(app.exec_())
    return 0

if __name__ == "__main__":
    main()
