#!/usr/bin/env python3
##
## HACKATOWN PROJECT, 2021
## Hackatown-2021
## File description:
## main file
##

import sys
import folium

from ClassAerialMap import AerialMap
from ClassMainWindow import MainWindow
from PySide2 import QtCore, QtWidgets
from PySide2.QtGui import QIcon
from PySide2.QtWidgets import QApplication, QMainWindow, QVBoxLayout, QWidget
from PySide2.QtCore import QFile
from PySide2.QtUiTools import QUiLoader
from PyQt5.QtWebEngineWidgets import QWebEngineView

if __name__ == "__main__":
    QtCore.QCoreApplication.setAttribute(QtCore.Qt.AA_ShareOpenGLContexts)
    app = QApplication([])
    widget = MainWindow()
    map_widget = AerialMap()
    map_widget.show()
    sys.exit(app.exec_())
